In [19]:
import os
import pandas as pd
import re

wd = "C:/Users/jakek/OneDrive - University of Connecticut/1-Projects/frm2/"
os.chdir(wd)

csv_path = wd + "results/" + ".csv/" + "frm2-aid_apicoplast-inheritance-quantification.csv"

print(f'Current working directory: {os.getcwd()}')
print(f'CSV path: {csv_path}')

Current working directory: C:\Users\jakek\OneDrive - University of Connecticut\1-Projects\frm2
CSV path: C:/Users/jakek/OneDrive - University of Connecticut/1-Projects/frm2/results/.csv/frm2-aid_apicoplast-inheritance-quantification.csv

In [20]:
csv = pd.read_csv(csv_path)
csv.head()

,img,treatment,cellStage,inheritanceDefect,note
0,2021-11-26_frm2-aid_cpn60_ctrl_01.tif,Control,Elongation,0,NaN
1,2021-11-26_frm2-aid_cpn60_ctrl_02.tif,Control,Elongation,0,NaN
2,2021-11-26_frm2-aid_cpn60_ctrl_03.tif,Control,Elongation,0,NaN
3,2021-11-26_frm2-aid_cpn60_ctrl_04.tif,Control,Elongation,0,NaN
4,2021-11-26_frm2-aid_cpn60_ctrl_05.tif,Control,NaN,0,NaN

In [21]:
ctrl = re.compile(".*ctrl.*")
kd = re.compile(".*kd.*")

csv.loc[csv['img'].str.contains('ctrl'), 'treatment'] = 'Control'
csv.loc[csv['img'].str.contains('kd'), 'treatment'] = 'FRM2-KD'

csv.head()

,img,treatment,cellStage,inheritanceDefect,note
0,2021-11-26_frm2-aid_cpn60_ctrl_01.tif,Control,Elongation,0,NaN
1,2021-11-26_frm2-aid_cpn60_ctrl_02.tif,Control,Elongation,0,NaN
2,2021-11-26_frm2-aid_cpn60_ctrl_03.tif,Control,Elongation,0,NaN
3,2021-11-26_frm2-aid_cpn60_ctrl_04.tif,Control,Elongation,0,NaN
4,2021-11-26_frm2-aid_cpn60_ctrl_05.tif,Control,NaN,0,NaN

In [22]:
csv.to_csv(csv_path, index=False)

In [23]:
ctrl_counts = {}
kd_counts = {}

ctrl_counts['total'] = len(csv.loc[csv['treatment'] == 'Control'])
kd_counts['total'] = len(csv.loc[csv['treatment'] == 'FRM2-KD'])

ctrl_counts['defects'] = len(csv.loc[(csv['treatment'] == 'Control') & (csv['inheritanceDefect'] == 1)])
kd_counts['defects'] = len(csv.loc[(csv['treatment'] == 'FRM2-KD') & (csv['inheritanceDefect'] == 1)])

ctrl_defect_percent = ctrl_counts['defects'] / ctrl_counts['total'] * 100
kd_defect_percent = kd_counts['defects'] / kd_counts['total'] * 100

defect_notes = csv.loc[csv['inheritanceDefect'] == 1, ['img', 'note']]
defect_notes

,img,note
29,2024-09-30_frm2-aid_cpn60_kd_05.tif,leftmost has 2 apicoplast
33,2024-09-30_frm2-aid_cpn60_kd_09.tif,bottom left parasite has no daughters or apico...
39,2024-09-30_frm2-aid_cpn60_kd_15.tif,apicoplast doesn't look like its segregating p...
41,2024-09-30_frm2-aid_cpn60_kd_17.tif,basal apicoplast
44,2024-09-30_frm2-aid_cpn60_kd_20.tif,"4 parasite vac, 9 apicoplasts"
48,2024-09-30_frm2-aid_cpn60_kd_24.tif,basal apicoplast
49,2024-09-30_frm2-aid_cpn60_kd_25.tif,apicoplast nearly completely fragmented
50,2024-09-30_frm2-aid_cpn60_kd_26.tif,"left parasite looks like it has 4 daughters, n..."
51,2024-09-30_frm2-aid_cpn60_kd_27.tif,"5 parasite vac, one really small with no apico..."
59,2024-09-30_frm2-aid_cpn60_kd_35.tif,"3 have apicoplast, 1 apicoplast looks to be in rb"

In [27]:
quote_from_tosetti_2019 = (
    "FRM2-KO parasites exhibited a defect in apicoplast inheritance (Figure 2F) ",
    "while the segregation of the Golgi was unaffected (Figure 2—figure supplement 2B). ",
    "The phenotype was partial; with about ~30% of vacuoles displaying a proper distribution ",
    "of apicoplast in all the parasites,~50% of the vacuoles showing at least one parasite ",
    "lacking the apicoplast, and ~20% with all the parasites lacking the apicoplast ",
    "(resulting from the reinvasion of parasites lacking the apicoplast) (Figure 2G)."
)

# Combine all the print statements into one
output = f"""
Percentages of images with an apicoplast inheritance defect.

Only images with a verifiable missing apicoplast were marked as having a defect.

Control: {ctrl_defect_percent:.0f}% ({ctrl_counts["defects"]}) defects among {ctrl_counts["total"]} images
FRM2-KD: {kd_defect_percent:.0f}% ({kd_counts["defects"]}) defects among {kd_counts["total"]} images

Defect notes:
"""

# Add defect notes
for i, row in defect_notes.iterrows():
    output += f'{row["img"]}: {row["note"]}\n'

# Add the quote
output += "\nquote from Tosetti et al. 2019:\n"
output += '"'
output += "\n".join(quote_from_tosetti_2019)
output += '"'

print(output)

Percentages of images with an apicoplast inheritance defect.

Only images with a verifiable missing apicoplast were marked as having a defect.

Control: 0% (0) defects among 25 images
FRM2-KD: 29% (10) defects among 35 images

Defect notes:
2024-09-30_frm2-aid_cpn60_kd_05.tif: leftmost has 2 apicoplast
2024-09-30_frm2-aid_cpn60_kd_09.tif: bottom left parasite has no daughters or apicoplast
2024-09-30_frm2-aid_cpn60_kd_15.tif: apicoplast doesn't look like its segregating properly, apicoplast in rb
2024-09-30_frm2-aid_cpn60_kd_17.tif: basal apicoplast
2024-09-30_frm2-aid_cpn60_kd_20.tif: 4 parasite vac, 9 apicoplasts
2024-09-30_frm2-aid_cpn60_kd_24.tif: basal apicoplast
2024-09-30_frm2-aid_cpn60_kd_25.tif: apicoplast nearly completely fragmented
2024-09-30_frm2-aid_cpn60_kd_26.tif: left parasite looks like it has 4 daughters, not 2 mothers overlapped, only 1 mother conoid visible, unless the other is missing a conoid
2024-09-30_frm2-aid_cpn60_kd_27.tif: 5 parasite vac, one really small with no apicoplast, mislocalized apicoplasts
2024-09-30_frm2-aid_cpn60_kd_35.tif: 3 have apicoplast, 1 apicoplast looks to be in rb

quote from Tosetti et al. 2019:
"FRM2-KO parasites exhibited a defect in apicoplast inheritance (Figure 2F)
while the segregation of the Golgi was unaffected (Figure 2—figure supplement 2B).
The phenotype was partial; with about ~30% of vacuoles displaying a proper distribution
of apicoplast in all the parasites,~50% of the vacuoles showing at least one parasite
lacking the apicoplast, and ~20% with all the parasites lacking the apicoplast
(resulting from the reinvasion of parasites lacking the apicoplast) (Figure 2G)."